- name: setting up mysql server
  hosts: db
  become: true
  vars:
    login_host: db.surya-devops.site
  vars_prompt:
    - name: root_password
      prompt: please enter mysql root password
      private: no
  tasks:
    - name: install mysql-server
      ansible.builtin.dnf:
        name: mysql-server
        state: present
    
    - name: enable and start mysql
      ansible.builtin.service:
        name: mysql
        state: started
        enabled: yes
    
    - name: install python & mysql dependencies
      ansible.builtin.pip:
        name:
        - PyMySQL
        - cryptography
        executable: pip3.9 
    
    - name: check if root password is setup or not
      community.mysql.mysql_info:
        login_user: root
        login_password: "{{ root_password }}"
        login_host: "{{ login_host }}"
        filter: version
      ignore_errors: true
      register: mysql_connection_output

    - name: setup root password if not set
      ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ root_password }}"
      when: mysql_connection_output.failed is true
